### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wifi-left** [zkitefly/Unlisted-versions-of-Minecraft#1]
建议同步到 GitLab
对国内特别友好，速度也超级快（比Gitee都快）
还有仓库文件夹建议用英文，
有些时候URL包含中文会出bug。
以及有一个总的 json 文件列出所有特殊版本名称方便枚举。
（GitHub Action 很好玩的，试试？[doge]）

**Comment by zkitefly** [comment]
- [ ] 建议同步到 GitLab
对国内特别友好，速度也超级快（比Gitee都快）

- [ ] 还有仓库文件夹建议用英文，
有些时候URL包含中文会出bug。

- [ ] 以及有一个总的 json 文件列出所有特殊版本名称方便枚举。

（GitHub Action 很好玩的，试试？[doge]）
